$background = 050404
$onBackground = e6e1e2
$surface = 050404
$surfaceDim = 050404
$surfaceBright = 101010
$surfaceContainerLowest = 030303
$surfaceContainerLow = 070707
$surfaceContainer = 090909
$surfaceContainerHigh = 0c0c0c
$surfaceContainerHighest = 0f0f0f
$onSurface = e6e1e2
$surfaceVariant = 141313
$onSurfaceVariant = cac5cb
$outline = 938f96
$outlineVariant = 48464b
$inverseSurface = e6e1e2
$inverseOnSurface = 313031
$shadow = 000000
$scrim = 000000
$surfaceTint = 282828
$primary = cac4d2
$primaryDim = ece5f4
$onPrimary = 322f3a
$primaryContainer = 514d59
$onPrimaryContainer = c5becd
$inversePrimary = 615c69
$primaryFixed = e7e0ef
$primaryFixedDim = cac4d2
$onPrimaryFixed = 1d1a24
$onPrimaryFixedVariant = 494551
$secondary = cac5cb
$secondaryDim = e6e1e7
$onSecondary = 322f34
$secondaryContainer = 4b484d
$onSecondaryContainer = bbb7bd
$secondaryFixed = e6e1e7
$secondaryFixedDim = cac5cb
$onSecondaryFixed = 1c1b1f
$onSecondaryFixedVariant = 48464b
$tertiary = d8c1c9
$tertiaryDim = f8dfe8
$onTertiary = 3b2c33
$tertiaryContainer = 5b4a51
$onTertiaryContainer = d1bbc3
$tertiaryFixed = f5dce5
$tertiaryFixedDim = d8c1c9
$onTertiaryFixed = 25181e
$onTertiaryFixedVariant = 534249
$error = ffb4ab
$errorDim = ff554a
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryPaletteKeyColor = 7a7582
$secondaryPaletteKeyColor = 79767c
$tertiaryPaletteKeyColor = 5b4a51
$neutralPaletteKeyColor = 797677
$neutralVariantPaletteKeyColor = 79767c
$errorPaletteKeyColor = de3730
$primary_paletteKeyColor = 7a7582
$secondary_paletteKeyColor = 79767c
$tertiary_paletteKeyColor = 5b4a51
$neutral_paletteKeyColor = 797677
$neutral_variant_paletteKeyColor = 79767c
$term0 = 080808
$term1 = c465ff
$term2 = ffbac2
$term3 = ffdcf2
$term4 = a1a7d8
$term5 = c09be5
$term6 = 9dceff
$term7 = e8d3de
$term8 = ac9fa9
$term9 = d48aff
$term10 = ffd2d5
$term11 = fff0f6
$term12 = bac0dd
$term13 = d4b2f0
$term14 = bae0ff
$term15 = ffffff
$rosewater = f9eef8
$flamingo = ecddf1
$pink = e9d5ff
$mauve = cbb4ff
$red = cfa1f6
$maroon = d2b3e8
$peach = e9c0f3
$yellow = ffecf3
$green = c8e3ff
$teal = d9deff
$sky = d6d8ff
$sapphire = c1c2ff
$blue = bdb4ff
$lavender = d1c5ff
$klink = 807ed1
$klinkSelection = 827ed0
$kvisited = 8f6ed5
$kvisitedSelection = 916dd4
$knegative = b260f5
$knegativeSelection = b55ff3
$kneutral = db8aff
$kneutralSelection = de88ff
$kpositive = 60adff
$kpositiveSelection = 60adff
$text = e6e1e2
$subtext1 = cac5cb
$subtext0 = 938f96
$overlay2 = 1c1c1c
$overlay1 = 191919
$overlay0 = 161616
$surface2 = 121212
$surface1 = 0d0d0d
$surface0 = 070606
$base = 010000
$mantle = 010000
$crust = 010000
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
