$background = 040503
$onBackground = e4e3da
$surface = 040503
$surfaceDim = 040503
$surfaceBright = 111010
$surfaceContainerLowest = 030302
$surfaceContainerLow = 070806
$surfaceContainer = 090907
$surfaceContainerHigh = 0c0c0b
$surfaceContainerHighest = 100f0f
$onSurface = e4e3da
$surfaceVariant = 131410
$onSurfaceVariant = c7c8b8
$outline = 909283
$outlineVariant = 46483c
$inverseSurface = e4e3da
$inverseOnSurface = 30312b
$shadow = 000000
$scrim = 000000
$surfaceTint = 242b0e
$primary = bece88
$primaryDim = e5f6ac
$onPrimary = 293500
$primaryContainer = 899858
$onPrimaryContainer = 242e00
$inversePrimary = 56642a
$primaryFixed = daeaa2
$primaryFixedDim = bece88
$onPrimaryFixed = 171e00
$onPrimaryFixedVariant = 3f4c14
$secondary = c4caa8
$secondaryDim = e0e6c3
$onSecondary = 2d331b
$secondaryContainer = 464c32
$onSecondaryContainer = b6bc9b
$secondaryFixed = e0e6c3
$secondaryFixedDim = c4caa8
$onSecondaryFixed = 191e08
$onSecondaryFixedVariant = 444930
$tertiary = 99d3af
$tertiaryDim = bdf9d3
$onTertiary = 003921
$tertiaryContainer = 659d7c
$onTertiaryContainer = 00311c
$tertiaryFixed = b5f0ca
$tertiaryFixedDim = 99d3af
$onTertiaryFixed = 002111
$onTertiaryFixedVariant = 175035
$error = ffb4ab
$errorDim = ff554a
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryPaletteKeyColor = 6f7d40
$secondaryPaletteKeyColor = 747a5d
$tertiaryPaletteKeyColor = 659d7c
$neutralPaletteKeyColor = 787771
$neutralVariantPaletteKeyColor = 76786a
$errorPaletteKeyColor = de3730
$primary_paletteKeyColor = 6f7d40
$secondary_paletteKeyColor = 747a5d
$tertiary_paletteKeyColor = 659d7c
$neutral_paletteKeyColor = 787771
$neutral_variant_paletteKeyColor = 76786a
$term0 = 080808
$term1 = a19200
$term2 = c1d660
$term3 = e7ed70
$term4 = 94b480
$term5 = c6a844
$term6 = b8d386
$term7 = dbd9c2
$term8 = a5a391
$term9 = bbaa00
$term10 = d0e95e
$term11 = f3fd72
$term12 = b7c6a2
$term13 = d2bf69
$term14 = cae58e
$term15 = ffffff
$rosewater = f7f1e1
$flamingo = eae2c1
$pink = ffd79d
$mauve = ffad7f
$red = cbb33f
$maroon = cfbf73
$peach = d5d185
$yellow = f2f5c3
$green = cdeb92
$teal = c7eaa8
$sky = bae8a5
$sapphire = 9dd692
$blue = 75cf9d
$lavender = 89dcc6
$klink = 519655
$klinkSelection = 519655
$kvisited = c06b00
$kvisitedSelection = c06b00
$knegative = 9a8800
$knegativeSelection = 998800
$kneutral = b5af00
$kneutralSelection = b5af00
$kpositive = 88b839
$kpositiveSelection = 88b83a
$text = e4e3da
$subtext1 = c7c8b8
$subtext0 = 909283
$overlay2 = 1c1c1c
$overlay1 = 191919
$overlay0 = 161615
$surface2 = 121211
$surface1 = 0d0e0b
$surface0 = 060705
$base = 000100
$mantle = 000100
$crust = 000100
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
